# BASE
FROM alpine
# RUN
RUN apk add nginx; \
    #mkdir /run/nginx/; \
    echo "<h1>Hello world!</h1>" > /var/www/localhost/htdocs/index.html;
# CONFIGUTATIONS
# nginx configuration
ADD $PWD/app/config/default.conf /etc/nginx/http.d/default.conf
# keys and certs
ADD $PWD/app/config/*.key /etc/ssl/private/
ADD $PWD/app/config/*.crt /etc/ssl/certs/
WORKDIR /var/www/localhost/htdocs
# ENTRYPOINT
COPY $PWD/app/config/entrypoint.sh /usr/local/bin
RUN chmod +x /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/bin/sh", "/usr/local/bin/entrypoint.sh"]
# EXPOSE PORTS
EXPOSE 80
EXPOSE 443
# RUN COMMAND
CMD ["/bin/sh", "-c", "nginx -g 'daemon off;'; nginx -s reload;"]
