resource_group_name         = "ofer_test1"
resource_group_location     = "West Europe"
virtual_network_name        = "vnet-ofer"
subnet_name                 = "subnet-ofer"
public_ip_name              = "publicip-ofer"
network_security_group_name = "nsgp-ofer"
network_interface_name      = "nic-ofer"
linux_virtual_machine_name  = "linuxvm-ofer"
